"""Descrição da migration

Revision ID: 4d59442cffa7
Revises: d79d8429157e
Create Date: 2025-07-08 18:44:38.480651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d59442cffa7'
down_revision: Union[str, Sequence[str], None] = 'd79d8429157e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividade', sa.Column('data_previsa', sa.Date(), nullable=True))
    op.drop_column('atividade', 'data_prevista')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividade', sa.Column('data_prevista', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('atividade', 'data_previsa')
    # ### end Alembic commands ###
