"""Remover tabelas teste e teste2

Revision ID: 4fd4b377b09c
Revises: c2cbf36053ed
Create Date: 2025-07-08 19:35:56.918354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd4b377b09c'
down_revision: Union[str, Sequence[str], None] = 'c2cbf36053ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teste')
    op.drop_table('teste2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('teste2_pkey'))
    )
    op.create_table('teste',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('teste_pkey'))
    )
    # ### end Alembic commands ###
